Feat - CI/CD workflow build and publish cloud dockerfile
PrestaShop/distribution-api pull request #12
Opened 2022-04-26 13:00 UTC by MaxencePerrinPrestashop

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Reworked CI/CD to build cloud.Dockerfile image and push to artifact registry, then call terraform repository to apply configuration
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | Create pull request, add "integration-deployment" label to trigger github action workflow
| Possible impacts? | Update cloud run instances with new image

2022-04-28 15:57 UTC, djodjo3 requested changes

2022-04-29 13:08 UTC, atomiix approved these changes

2022-05-02 07:59 UTC, Progi1984 approved these changes

2022-05-02 12:42 UTC, merged

2022-05-02 12:43 UTC, atomiix commented
Thanks @MaxencePerrinPrestashop